server:
  port: 8084

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or `validate` or `none` in prod
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json
          
logging:
  level:
    org.springframework.security: DEBUG

